### ISSUE TITLE
Feedback 2

### ISSUE THREAD

**Issue by majbrit** [majbrit/MKSS1#8]
# Lab:
- [ ] use persistence-oriented 
- use Hashmap
- in getAll return a copy of the orders
- [ ] price formatting not inside the item class

#Mr Teacher:
## Task 1 Factory
- [ ] abstract product classes
- [ ] createProduct should have return type product
- [ ] createService should have return type Service
## Task 2 Remote Control
- [ ] don't store states in the command classes
- [ ] no toggle command, it should be two command classes instead for example on and off
- [ ] previous and next function calls in wrong classes
##Task 3
Everything is good
